config/routes.rb
Rails.application.routes.draw do
  resources :dishes
  resources :restaurants
  root 'dishes#index'
  get 'search' => "dishes#search"
  get 'dishes/:id' => "dishes#show"
  get 'restaurants/:id' => "restaurants#show"
  get 'filter'=> "dishes#filters"

	get '/dish_list' => 'dishes#dish_list'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_attached_file :image
  has_and_belongs_to_many :restaurants

  has_attached_file :image, styles: {
        thumb: '10x10>',
        medium: '50x50>',
        processors: [:thumbnail]}, default_url: "/images/:style/missing.png" 
  validates_attachment :image, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)},
  attachment_size: { less_than: 5.megabytes }
  validates :name, :price, :rating, :tagging_id, presence: true
end

app/models/dishes_restaurant.rb
class DishesRestaurant < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :location
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode
  has_many :restaurants

end

app/models/rating.rb
class Rating < ApplicationRecord
  after_save :rating_avg
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_and_belongs_to_many :dishes
  belongs_to :location
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  validates :tag_name, presence: true, length: { in:4..6 }
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  def index
    @dishes_query = Dish.all
    puts "success"
  end

  def search
  
    @locations = []
    
    gon.locations = @locations

    @dishes_search = Dish.where('name LIKE ?',"%#{params[:name]}%")

    @dishes_search.find_each do |dish|
      dish.restaurants.each do |res|
        @locations.push(res.location)
      end
    end 
   
    
    @taggings = Tagging.all

    if params[:filter]
      @dishes_search =  Dish.order(params[:filter]).where('name LIKE ?',"%#{params[:name]}%")
     
    elsif params[:ratingfilter]
      @dishes_search = Dish.where('rating > ? ', params[:ratingfilter] ).where('name LIKE ?',"%#{params[:name]}%")

    elsif params[:taggingfilter]
      @dishes_search =  Dish.where(tagging_id: params[:taggingfilter]).where('name LIKE ?',"%#{params[:name]}%")
          
    elsif params[:min_rangefilter] and params[:max_rangefilter]
      @dishes_search =  Dish.where('price BETWEEN ? AND ?', params[:min_rangefilter], params[:max_rangefilter]).where('name LIKE ?',"%#{params[:name]}%")

    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def dish_list
    @dish = Dish.all
    render :json => @dish
  end

  private

  def dish_params
   params.permit(:name, :filter)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  end
  def show
    @restarent = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dishes/_address.html.erb
<% locations.each do |f|%>
  <%= f. latitude %>
  <%= f. longitude %>
<% end %>

app/views/dishes/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h3 class="footer_info">Do more with the app. Download it today!</h3><br>
        <div class="store_block">
          <%= link_to(image_tag('googleplaystore.png', :class=>"app_store")) %>
          <%= link_to(image_tag('applestore.png', :class=>"app_store")) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="footer_image">
           <%= image_tag('phone-footer.png') %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/dishes/_header.html.erb
<div class="nav_style">
  <div class="container">
    <nav class="navbar navbar-expand-sm ">
      <%= link_to(image_tag('logo.png', class: "navbar-brand"),"#")%>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <div class=" location_dropdown dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              SELECT LOCATION
            </div>
            <div class="dropdown-menu location_search_dropdown">
              <div>
                <%= form_tag(search_path , method: :get, enforce_utf8: false) do %>
                <%= text_field_tag :name, nil, class: "dropdown_input_style", :placeholder => 'location' %>
                
                  <%= button_tag( :name=>nil , class: "location_search_btn" ) do %>
                    <%= image_tag('search_icon.png') %>
                  <% end %>
              <% end %>
              </div>
            </div>
          </li>
          <div class="nav_right">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "CONTACT US", "#", :class=>"nav_item_right" %>
              </li> 
              <li class="nav-item">
                <%= link_to "SEARCH", dishes_path, :class=>"nav_item_right" %>
              </li> 
            </ul>
         </div>
        </ul>
    </nav> 
  </div>
</div>







 

app/views/dishes/_list.html.erb
<% dishes.each_slice(2) do |works| %>
  <div class="row row_space">
    <% works.each do |dish| %>
      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <figure class="figure-style">
          <div class="search_image_style">
            <%= link_to(image_tag(dish.image.url(:original), class: "image-size"), dish_path(dish)) %>
          </div>
          
            <h1 class="dish_name"><%= dish.name%></h1>
             <%= dish.restaurants.find_each do |restaurant| %>
            <h4 class="restaurent_name">
              <%= link_to restaurant.name, restaurant_path(restaurant), class: "link_style" %>
            </h4>
            <p class="price_style"><i class="fa fa-inr"></i><%= dish.price %></p>
            <p class="rating_sym_style">
              <%= image_tag('heart.png')%>  &nbsp<span><%= dish.rating %></span><br>
              <span class="vote_count">1 vote</span>
            </p>

            <div class="dish_location">
              <div>
                <p><span class="dish_location_style"><%= fa_icon "map-marker" %></span><%= restaurant.location.location %></p>
              </div>
            </div>
          <% end %>
        </figure>
      </div>
    <% end %>
  </div>
<% end %>

app/views/dishes/index.html.erb
<div class="search_background">
  <%= image_tag(('back.png'),:class=>"img-fluid search_block")%>
</div>
<div>
  <div class="search_text_block">
    <h1>What do you <em>really </em>feel like? </h1>
  </div>
  <div class="search_input">
     <%= form_tag(search_path , method: :get, enforce_utf8: false) do %>
        <%= text_field_tag :name, nil, class:"input_style", :placeholder => 'Chips and burgers' %>
        <span><%= image_tag('search_icon.png') %></span> <%= submit_tag 'SEARCH',:name=>nil, class:"search_btn" %>
      <% end %>
  </div>
</div>

  <div class="noticer" align="center">
    <span class="dish_identifier">TOP RATED DISHES</span>
  </div>
<div class="main_content">
  <div class="container">
    <% if @dishes_query %>
    <% @dishes_query.each_slice(3) do |works| %>
      <div class="row row_space">
      <% works.each do |dish|%>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
          <figure class="figure-style">
            <div class="dish_image">
              <%= link_to(image_tag(dish.image.url(:original),class: "image-size"), dish_path(dish)) %>
               </div>
                <h1 class="dish_name"><%= dish.name%></h1>
                 <%= dish.restaurants.find_each do |restaurant| %>

                <h4 class="restaurent_name">
                  <%= link_to restaurant.name, restaurant_path(restaurant), class: "link_style" %>   
                </h4>

                <p class="price_style">&#8377;<%= dish.price %></p>

                <div class="rating_background">
                  <p class="rating_sym_style"><%= image_tag('heart.png')%>  &nbsp<%= dish.rating %><br>
                  <span class="vote_count">1 vote</span>
                  </p>
                </div>

                <div class="dish_location">
                  <div>
                    <p><span class="dish_location_style"><%= fa_icon "map-marker" %></span><%= restaurant.location.location %></p>
                  </div>
                </div>
              <% end %>
          </figure>
        </div>
      <% end %>
    </div>
    <% end %>
  <% end %>
  </div>
</div>
<div class="see_more">
  <div align="center">
    <%= link_to "SEE MORE FOOD", "#" ,class: "btn btn-outline-secondary btn_style"%>
  </div>
</div>
<%= render 'footer' %>

app/views/dishes/search.html.erb
<div class="container-fluid">
  <div class= "search_main">
    <div class="search_page">
      <% if @dishes_search.length == 0 %>
        <h4 align="center">No result found</h4>
      <% else %>
        <div class="row">
          <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6 ">
            <div class="row filter_block">
              <div class="col-md-4">
                <div class="row">
                  <div class="col-md-4">
                    <p>FILTER</p>
                  </div>
                  <div class="col-md-8">
                     <%= select_tag("filter", options_for_select([["RATING","rating"],["PRICE","price"]]), {prompt: 'SORT BY', :name => "filter", :class=>"form-control select_style", id:"filter", remote: true} ) %>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                 <%= select_tag("ratings", options_for_select([["3+",3],["4+",4],["5+",5]]),{prompt: 'ALL RATINGS', :name => "ratings", id:"rating_filter", :class=>"form-control select_style"} ) %>

              </div>
              <div class="col-md-4">
                <div class="dropdown">
                  <button class="btn multi_select dropdown-toggle" type="button" data-toggle="dropdown"><span id="taggings_list">ALL DIETARY REQUIREMENT</span>
                  <span class="caret"></span></button>
                  <div class="dropdown-menu multi_drop_down">
                    <div class="search_multi_select">
                      <%= @taggings.find_each do |tagging| %>
                        <div class="multi_check"><%= check_box tagging.id,nil, :class=>"check_tagging", :id=>tagging.id, :name=>tagging.tag_name %> <span> <%= tagging.tag_name %></span></div>
                        <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="row slider_block">
              <p id="count"><%= @dishes_search.count %> RESULTS</p>
                <span><i class="fa fa-inr"></i><span id="range_min">10</span></span>
                <div id="slider"></div>
                <span><i class="fa fa-inr"></i><span id="range_max">1000</span></span>
            </div>

            <div class="row">
              <div class="container search_items_list">
                <%= render 'dishes/list', dishes: @dishes_search %>
              </div>
            </div>
          </div>
          
          <div class="col-md-6 col-lg-6" id="map_block_div">
            <div></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dishes/search.js.erb
$('.search_items_list').html('<%= j render "dishes/list", dishes: @dishes_search %>');
$('#count').text("<%= @dishes_search.count %> RESULTS")

app/views/dishes/show.html.erb
<div class="show_main_page">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 show_dish_name">
        <%= image_tag @dish.image.url(:original), :class=>"rounded-circle show_dish_icon" %>
        <span> <%= @dish.name %></span>
        <%= @dish.restaurants.find_each do |restaurant| %>
          <p><%= link_to restaurant.name, restaurant_path,:class=>"show_restaurant_name" %>
          </p>
      </div>
      <div class="col-md-9 show_dish_image">
        <figure class="show_figure_style">
          <div class="show_image">
            <%= image_tag @dish.image.url(:original),class: "show_image_size" %>
          </div>
        </figure>
        <h1 class="dish_name"><%= @dish.name %></h1>
        <h4 class="restaurent_name"><%= link_to restaurant.name, restaurant_path(restaurant), class: "link_style" %></h4>
        <div class="rating_background">
          <p class="rating_sym_style"><%= image_tag('heart.png')%>  &nbsp<%= @dish.rating %><br>
          <span class="vote_count">1 vote</span>
          </p>
        </div>
        <p class="price_style">&#8377;<%= @dish.price %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodfie</title>
    <%= favicon_link_tag 'icon.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBxBIfFGmL6adUEtytF2IYA10JZjQc5_sk&callback=initMap"
    async defer></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-marker-clusterer/1.0.0/markerclusterer_compiled.js"></script>

  </head>
  <body>
    <%= render 'header' %>
    <%= yield %>
  </body>
</html>

app/views/ratings/index.html.erb
<h1>Ratings#index</h1>
<p>Find me in app/views/ratings/index.html.erb</p>

app/views/restaurants/_header.html.erb
<div class="nav_style">
  <div class="container">
    <nav class="navbar navbar-expand-sm ">
      <%= link_to(image_tag('logo.png', class:"navbar-brand"),"#")%>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <div class=" location_dropdown dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              SELECT LOCATION
            </div>
            <div class="dropdown-menu">
              <%= form_tag(search_path , method: :get, enforce_utf8: false) do %>
                <%= text_field_tag :name, nil, class: "input_style", :placeholder => 'search pla' %>
                <span><%= image_tag('search_icon.png') %></span> <%= submit_tag 'SEARCH',:name=>nil, class: "search_btn" %>
              <% end %>
            </div>
          </li>
          <div class="nav_right">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "CONTACT US", "#", :class=>"nav_item_right" %>
              </li> 
              <li class="nav-item">
                <%= link_to "SEARCH", dishes_path, :class=>"nav_item_right" %>
              </li> 
            </ul>
         </div>
        </ul>
    </nav> 
  </div>
</div>







 

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p>

app/views/restaurants/show.html.erb
<%= @restarent.dishes.find_each do |dish| %>
  <%= dish.name %>
  <%= dish.id %>
  <%= dish.price %>
  <%= link_to(image_tag(dish.image.url(:medium)), dish_path(dish)) %>
<% end %>